name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.2'
          cache: true

      - name: pake_config
        working-directory: packages/pake_config
        run: |
          dart pub get
          dart analyze
          dart format --set-exit-if-changed .
          dart test

      - name: pake_cli
        working-directory: packages/pake_cli
        run: |
          dart pub get
          dart analyze
          dart format --set-exit-if-changed .
          dart test --timeout 60s

      - name: pake_shell
        working-directory: packages/pake_shell
        run: |
          flutter pub get
          flutter analyze
          dart format --set-exit-if-changed .
          flutter test
